name: ch2-complex-workflow-challenge

on: push
# Example 1: 1 Event with a Conditional
# push:
#   branches:
#     - develop
#     - master

# Example 2: Multi Events Conditionals
# push:
#   branches:
#     - develop
#     - master
# pull_request:
#   branches:
#     - master

# Other Conditionals:
# Ignore branches -> branches-ignore
# Use tags  ->       tags tags-ignore
# Special characters  -> 'feature/new-feature'
#                        'release/*'
#                        'm?ster'

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      run: date
  windows:
    name: windows
    runs-on: windows-latest
    steps:
    - name: Step one
      run: date
  macos:
    name: macos
    runs-on: macos-latest
    steps:
    - name: Step one
      run: date
  depends:
    name: depends
    needs: [ubuntu, windows, macos]
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      run: date
  # job3:
  #   name: Third job
  #   needs: [job1, job2]

